<?php

namespace SV\Reset\Model;

use SV\Reset\Reset;

class Product extends Reset
{

    /** @var array */
    protected $tables = [
        'catalog_category_product',
        'catalog_category_product_index',
        'catalog_category_product_index_replica',
        'catalog_category_product_index_tmp',
        'catalog_product_bundle_option',
        'catalog_product_bundle_option_value',
        'catalog_product_bundle_price_index',
        'catalog_product_bundle_selection',
        'catalog_product_bundle_selection_price',
        'catalog_product_bundle_stock_index',
        'catalog_product_entity',
        'catalog_product_entity_datetime',
        'catalog_product_entity_decimal',
        'catalog_product_entity_gallery',
        'catalog_product_entity_int',
        'catalog_product_entity_media_gallery',
        'catalog_product_entity_media_gallery_value',
        'catalog_product_entity_media_gallery_value_to_entity',
        'catalog_product_entity_media_gallery_value_video',
        'catalog_product_entity_text',
        'catalog_product_entity_tier_price',
        'catalog_product_entity_varchar',
        'catalog_product_frontend_action',
        'catalog_product_index_eav',
        'catalog_product_index_eav_decimal',
        'catalog_product_index_eav_decimal_idx',
        'catalog_product_index_eav_decimal_replica',
        'catalog_product_index_eav_decimal_tmp',
        'catalog_product_index_eav_idx',
        'catalog_product_index_eav_replica',
        'catalog_product_index_eav_tmp',
        'catalog_product_index_price',
        'catalog_product_index_price_bundle_idx',
        'catalog_product_index_price_bundle_opt_idx',
        'catalog_product_index_price_bundle_opt_tmp',
        'catalog_product_index_price_bundle_sel_idx',
        'catalog_product_index_price_bundle_sel_tmp',
        'catalog_product_index_price_bundle_tmp',
        'catalog_product_index_price_cfg_opt_agr_idx',
        'catalog_product_index_price_cfg_opt_agr_tmp',
        'catalog_product_index_price_cfg_opt_idx',
        'catalog_product_index_price_cfg_opt_tmp',
        'catalog_product_index_price_downlod_idx',
        'catalog_product_index_price_downlod_tmp',
        'catalog_product_index_price_final_idx',
        'catalog_product_index_price_final_tmp',
        'catalog_product_index_price_idx',
        'catalog_product_index_price_opt_agr_idx',
        'catalog_product_index_price_opt_agr_tmp',
        'catalog_product_index_price_opt_idx',
        'catalog_product_index_price_opt_tmp',
        'catalog_product_index_price_replica',
        'catalog_product_index_price_tmp',
        'catalog_product_index_tier_price',
        'catalog_product_index_website',
        'catalog_product_link',
        'catalog_product_link_attribute',
        'catalog_product_link_attribute_decimal',
        'catalog_product_link_attribute_int',
        'catalog_product_link_attribute_varchar',
        'catalog_product_link_type',
        'catalog_product_option',
        'catalog_product_option_price',
        'catalog_product_option_title',
        'catalog_product_option_type_price',
        'catalog_product_option_type_title',
        'catalog_product_option_type_value',
        'catalog_product_relation',
        'catalog_product_super_attribute',
        'catalog_product_super_attribute_label',
        'catalog_product_super_link',
        'catalog_product_website',
        'catalog_url_rewrite_product_category',
        'catalogrule_product',
        'catalogrule_product_price',
        'catalogrule_product_price_replica',
        'catalogrule_product_replica',
        'product_alert_price',
        'product_alert_stock',
        'report_compared_product_index',
        'report_viewed_product_aggregated_daily',
        'report_viewed_product_aggregated_monthly',
        'report_viewed_product_aggregated_yearly',
        'report_viewed_product_index',
        'salesrule_product_attribute',
        'search_query',
        'wishlist',
        'wishlist_item',
        'wishlist_item_option',
    ];

    /** @var array */
    protected $indexes = [
        'catalog_category_product',
        'catalog_product_category',
        'catalog_product_price',
        'catalog_product_attribute',
        'cataloginventory_stock',
        'catalogsearch_fulltext',
    ];

    /** @var string */
    protected $rewriteType = 'product';

}